# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
