# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_useragent_date'),
    ]

    operations = [
    ]
