# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_auto_20161214_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragent',
            old_name='date',
            new_name='date_create',
        ),
    ]
